trigger:
- '*'

pool:
  vmImage: 'ubuntu-18.04'
  demands:
  - npm

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '3.1.300'
  System.Debug: true

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
  inputs:
    version: '$(dotnetSdkVersion)'

- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Visual Studio Enterprise – MPN(d31ac6d8-ac40-408d-9925-eae1a20c99b7)'
    KeyVaultName: 'TestKeyVault-Alterra'
    SecretsFilter: '*'

- task: CmdLine@2
  inputs:
    script: |
      echo "my pipeline variable is $(test-variable)"
      echo $(test-123) > secret.txt      
      echo "##vso[task.setvariable variable=tempvariable]does this work?"
      echo "my key vault variable is $(tempvariable)"