trigger:
- '*'

pool:
  vmImage: 'ubuntu-18.04'
  demands:
  - npm

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '3.1.300'
  System.Debug: false

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
  inputs:
    version: '$(dotnetSdkVersion)'
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)/Templates'
  inputs:
    SourceFolder: deployment
    Contents: '*.json'
    TargetFolder: '$(build.artifactstagingdirectory)/Templates'
- task: Npm@1
  displayName: 'npm custom'
  inputs:
    command: custom
    verbose: false
    customCommand: 'install --production'
- task: ArchiveFiles@2
  displayName: 'Archive $(Build.SourcesDirectory)'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
